spring:
    profiles:
        active: dev
    datasource:
        type: com.zaxxer.hikari.HikariDataSource
        url: jdbc:mysql://localhost:3306/groovy?useUnicode=true&characterEncoding=utf8&useSSL=false&autoReconnect=true
        username: root
        password: root
        hikari:
            data-source-properties:
                cachePrepStmts: true
                prepStmtCacheSize: 250
                prepStmtCacheSqlLimit: 2048
                useServerPrepStmts: true
    
    jpa: 
        database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
        database: MYSQL
        show-sql: false
        properties:
            hibernate.id.new_generator_mappings: true
            hibernate.cache.use_second_level_cache: false
            hibernate.cache.use_query_cache: false
            hibernate.generate_statistics: false
            hibernate.hbm2ddl.auto: update 
        hibernate:
            naming:
                physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    thymeleaf:
        cache: false
    resources:
      static-locations:
          - classpath:/META-INF/resources/
          - classpath:/resources/
          - classpath:/static/
          - classpath:/public/
          
    devtools: 
        restart:
            enabled: true
        livereload:
            enabled: false
         
logging: 
    level:
        ROOT: INFO
        
application:
   solrUrl: https://localhost:8080
   photoUrl: /images/profilePhoto/
   Storage: 
    sorlIndexLibrary: slowcity-admin
    mvFilePath: E:/slowcity/
    sorlUrl: slowcity-admin
    previewUrl: slowcity-admin
    solrContentUrl: slowcity-admin

